/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GraphData, GraphOptions, GraphSwimlaneData, XAxisData } from "./components/graph-component/draw/graph";
export namespace Components {
    interface GraphComponent {
        "data": {
    xaxis: XAxisData[];
    graphData: GraphData[];
    swimlaneData: GraphSwimlaneData[];
  };
        "options": GraphOptions;
    }
}
declare global {
    interface HTMLGraphComponentElement extends Components.GraphComponent, HTMLStencilElement {
    }
    var HTMLGraphComponentElement: {
        prototype: HTMLGraphComponentElement;
        new (): HTMLGraphComponentElement;
    };
    interface HTMLElementTagNameMap {
        "graph-component": HTMLGraphComponentElement;
    }
}
declare namespace LocalJSX {
    interface GraphComponent {
        "data"?: {
    xaxis: XAxisData[];
    graphData: GraphData[];
    swimlaneData: GraphSwimlaneData[];
  };
        "options"?: GraphOptions;
    }
    interface IntrinsicElements {
        "graph-component": GraphComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "graph-component": LocalJSX.GraphComponent & JSXBase.HTMLAttributes<HTMLGraphComponentElement>;
        }
    }
}
